import React from "react";
import CarItem from "./carItem";
export function BigSelector(){
    return(

        <div className="bigSelector">
            <div className="bidSelector-workspace ">
                <div className="flex-row">
                <CarItem text="Автомобили Peugeot"
                img=""
                count="0"/>
                <CarItem text="Автобусы Higer"
                img=""
                count="2"/>
                <CarItem text="Автобусы Zhongtong"
                img=""
                count="1"/>
                <CarItem text="Автомобили SHAANXI"
                img=""
                count="0"/>
                <CarItem text="Автомобили FAW Bestune"
                img=""
                count="3"/>
                 <CarItem text="Автомобили Vouah"
                img=""
                count="0"/>
                 <CarItem text="Автомобили EXEED"
                img=""
                count="3"/>
                 <CarItem text="Спецтехника SHACMAN"
                img=""
                count="3"/>
                 <CarItem text="Спецтехника CATMANN"
                img=""
                count="3"/>
                <CarItem text="Спецтехника Альфран"
                img=""
                count="0"/>
                <CarItem text="Спецтехника FAW"
                img=""
                count="3"/>
                <CarItem text="Спецтехника Sunward"
                img=""
                count="3"/>
                <CarItem text="Спецтехника ООО ПромТехСпецАвто"
                img=""
                count="1"/>
                <CarItem text="Спецтехника DongFeng"
                img=""
                count="1"/>
                <CarItem text="Автомобили BAIC"
                img=""
                count="3"/>
                <CarItem text="Автомобили ЮниСКАФ"
                img=""
                count="1"/>
                <CarItem text="Автомобили JETOUR"
                img=""
                count="3"/>
                <CarItem text="Спецтехника АЛЬФАРАН"
                img=""
                count="2"/>
                <CarItem text="Автомобили ZEEKR"
                img=""
                count="3"/>
                 <CarItem text="Спецтехника ROSSEL"
                img=""
                count="3"/>
                <CarItem text="Автомобили МАЗ"
                img=""
                count="3"/>
                <CarItem text="Автомобили Chery"
                img=""
                count="3"/>
                <CarItem text="Автомобили JAC"
                img=""
                count="3"/>
                <CarItem text="Спецтехника SANY от ООО АТС СаниБел"
                img=""
                count="2"/>
                <CarItem text="Спецтехника SANY от ООО ТПК Белдозер"
                img=""
                count="2"/>
                <CarItem text="Автомобили HAVAL"
                img=""
                count="3"/>
                <CarItem text="Автомобили Audi"
                img=""
                count="0"/>
                <CarItem text="Автомобили BMW"
                img=""
                count="3"/>
                <CarItem text="Спецтехника CASE"
                img=""
                count="0"/>
                <CarItem text="Автомобили Citroen"
                img=""
                count="0"/>
                <CarItem text="Автомобили Ford"
                img=""
                count="0"/>
                <CarItem text="Автомобили GEELY"
                img=""
                count="1"/>
                <CarItem text="Автомобили Mitsubishi"
                img=""
                count="0"/>
                <CarItem text="Автомобили Nissan"
                img=""
                count="0"/>
                <CarItem text="Автомобили Porsche"
                img=""
                count="0"/>
                <CarItem text="Автомобили Volkswagen"
                img=""
                count="3"/>
                <CarItem text="Автомобили Volvo"
                img=""
                count="0"/>
                <CarItem text="Автомобили Hyundai"
                img=""
                count="0"/>
                <CarItem text="Автомобили Renault"
                img=""
                count="0"/>
                <CarItem text="Автомобили Kia"
                img=""
                count="3"/>
                <CarItem text="Автомобили LADA"
                img=""
                count="0"/>
                <CarItem text="Автомобили Opel"
                img=""
                count="0"/>
                <CarItem text="Автомобили ГАЗ"
                img=""
                count="1"/>
                <CarItem text="Автомобили УАЗ"
                img=""
                count="0"/>
                <CarItem text="Автомобили Toyota"
                img=""
                count="0"/>
                <CarItem text="Автомобили MAZDA"
                img=""
                count="1"/>
                <CarItem text="Спецтехника KOLUMAN"
                img=""
                count="0"/>
                </div>
              
            </div>
        </div>
    )
}

export default BigSelector;